version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    build: 
      context: .
    ports: 
      - "8081:80"
    networks: 
      - server-eth
  mysql_server:
    image: "mysql:8.0"
    container_name: mysqlserver
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "filmes"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "toor"
    volumes:
       - db_mysql:/var/mysql #change in case of errors
    networks:
      - server-eth
volumes:
  db_mysql:
networks:
  server-eth:
    driver: bridge