AWSTemplateFormatVersion: "2010-09-09"
Description: CTD - turma 6 - grupo 3 - Automatizar Bucket S3
Parameters:
 BucketName:
   Type: String
   Description: t6g625102022
Metadata:
 AWS::CloudFormation::Interface:
   ParametersGroup:
   - Label:
           default: Bucket S3
     Parameters:
     - BucketName
   ParametersLabel:
     BucketName:
       default: 'Nome do meu Bucket: '
Resources:
 S3Bucket:
   Type: AWS::S3::Bucket
   Properties:
     BucketName: !Ref BucketName
     PublicAccessBlockConfiguration:
       BlockPublicAcls: true
       BlockPublicPolicy: true
       IgnorePublicAcls: true
       RestrictPublicBuckets: true
     VersioningConfiguration:
       Status: Enabled